# Generated by Django 2.0.3 on 2018-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CreateService',
            new_name='ServiceConfig',
        ),
    ]
