# Generated by Django 2.0.3 on 2018-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0002_auto_20180313_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='svc_spec_selector',
            field=models.CharField(default='MyApps', max_length=32),
        ),
    ]
