# Generated by Django 2.0.3 on 2018-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_auto_20180313_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='svc_name',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='svc_port',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='svc_protocol',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='svc_spec_selector',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='svc_target_port',
        ),
    ]
